name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: [0.14.1]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}
    
    - name: Run tests
      run: zig build test
    
    - name: Build examples
      run: zig build
    
    - name: Check formatting
      run: zig fmt --check src/

  windows-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1
    
    - name: Run tests
      run: zig build test
    
    - name: Build examples
      run: zig build

  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1
    
    - name: Run tests
      run: zig build test
    
    - name: Build examples
      run: zig build
